#!/bin/sh
set -e
set -u

if [ -d ./supported ]; then
	SUPPORTED=./supported
else
	SUPPORTED=/usr/share/games/game-data-packager/supported
fi

if [ -f ./lib/game-data-packager-shared ]; then
	. ./lib/game-data-packager-shared
else
	. /usr/lib/game-data-packager/game-data-packager-shared
fi

supported() {
	echo "the following games are supported:"
	echo
	printf "\tname\tdescription\n"
	printf "\t----\t-----------\n"

	find $SUPPORTED -type f | grep -v '\.svn' | grep -v 'swp$' | sort |
	while read file; do
		. $file
		printf "\t%s\t%s\n" "$SHORTNAME" "$LONGNAME"
	done
}
options() {
	echo "game-data-packager arguments:"
	echo "        -n            not do not install the generated package (requires -d)"
	echo "        -d OUTDIR     write the generated .deb(s) to OUTDIR"
}

usage() {
	echo "usage:"
	printf "\tgame-data-packager [game-data-packager-args] game [game-args]\n"
	echo
	options
	echo
	supported
	echo
	echo "run game-data-packager [game] to see game-specific arguments."
	echo
}

DEBUG=TRUE
debug() {
	if [ -n "$DEBUG" ]; then
		echo "DEBUG: $*" >&2
	fi
}
warn() {
	echo "WARNING: $*" >&2
}

if [ $# -lt 1 ]; then
	usage >&2
	exit 1
fi

# package default settings
if [ -f "./etc/game-data-packager.conf" ]; then
	source "./etc/game-data-packager.conf"
else
	source "/etc/game-data-packager.conf"
fi
OUTDIR=""

# process command line arguments

# defaults
INSTALL="yes"
PRESERVE="no"

while [ $# -gt 1 ]; do
	case "$1" in 
		'-n')
			INSTALL="no"
			;;
		'-d')
			PRESERVE="yes"
			shift
			if [ $# -lt 2 ]; then
				echo "missing directory or game argument" >&2
				usage >&2
				exit 1
			fi
			OUTDIR="$1"
			;;
		'--')
			break;
			;;
		*) # possibly the game name
			break;
			;;
	esac
	shift
done

if [ "$INSTALL" = "no" -a "$PRESERVE" = "no" ]; then
	echo "if you specify -n, you must also specify -d." >&2
	exit 1
fi

debug "INSTALL=$INSTALL"
debug "PRESERVE=$PRESERVE"

GAME="$1"
if [ ! -f "$SUPPORTED/$GAME" ]; then
	echo "unknown option or game '$GAME'" >&2
	supported >&2
	exit 1
fi
source "$SUPPORTED/$GAME"

debug "short: $SHORTNAME"
debug "long: $LONGNAME"

# setup a working directory
WORKDIR=`mktemp -t -d game-data-packager.XXXXXX`
debug "WORKDIR=$WORKDIR"

# now the game's handler needs to be executed
shift
go "$@"

# TODO: OUTFILE not referenced before here in this file; we're
# assuming "go" will have defined it.

if [ "$PRESERVE" = "yes" ]; then
	echo "generated $OUTFILE."
fi

if [ "$INSTALL" = "yes" ]; then
	debug "invoking gdebi to install the package"
	install_deb "$OUTFILE"
fi

# cleanup
if [ "$PRESERVE" != "yes" ]; then
	rm "$OUTFILE"
fi
rmdir "$WORKDIR"
