#!/bin/bash
# copyright (c) 2006 Jon Dowland <jon@alcopop.org>
# distributed under the terms of the GNU Public Licence (GPL) v2 -
# see /usr/share/common-licenses/GPL-2 for details.

set -e

# doom-package: manage installation of doom2 IWAD into a debian system:
	# take the dummy doom2-wad .deb and insert the real IWAD.
	# saves the resulting .deb in the current directory

DATADIR="usr/share/games/doom-package"
DEB="/$DATADIR/doom2-wad_6_all.deb"

if [ -f ./game-package-shared ]; then
	. ./game-package-shared
else
	. /usr/lib/game-package/game-package-shared
fi

# takes one argument: the doom2.wad file
if [ -z "$1" -o ! -e "$1" ]; then
  diemsg="usage:
	make-wad-package /path/to/doom2.wad
Generates a .deb package for the doom2 IWAD file specified
on the command line."
  [ -e "$1" ] || echo "  $1 does not appear to exist"
  die "$diemsg"
fi
IWAD="$1"

# only supports `doom2.wad' so far
tmp=$(basename $IWAD)
[ "doom2.wad" = "$tmp" ] ||\
[ "DOOM2.WAD" = "$tmp" ] ||\
die "supplied IWAD must be called doom2.wad."

xOLDPWD=$(pwd)
WORKDIR=$(mktemp -dt make-wad-package.XXXXXX) ||\
	 die "error creating a working directory."

(
	set -e

	cp "$DEB" "$WORKDIR"
	cp "$IWAD" "$WORKDIR/doom2.wad"
	cd "$WORKDIR"

	DEB=$(basename "$DEB")
	IWAD=doom2.wad
	chmod 644 "$IWAD"

	slipstream "$DEB" "$DATADIR" "$IWAD"
	cp -a "$DEB" "$xOLDPWD"
)
RET=$?
rm -rf "$WORKDIR"
[ $RET -eq 0 ] || die "subshell exited abnormally" $RET
