.\" make-wad-package manpage; based on wtfm_example by branden robinson
.\" <http://people.debian.org/~branden/talks/wtfm/>
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; version 2.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
.\" Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with this library; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" See /usr/share/common-licenses/GPL-2
.\" 
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH make-wad-package 6 2006-10-01
.SH NAME
make\-wad\-package \- build a .deb from a doom IWAD
.
.SH SYNOPSIS
.B make\-wad\-package
.IR wadfile
.br
.SH DESCRIPTION
Doom requires both a doom-engine and doom data to play.
\fBmake\-wad\-package\fP converts the IWAD file from your
CD-ROM (or elsewhere) into a debian package which you can
then install.
.br
The resulting package satisfies the \fIdoom\-wad\fP package 
dependency, allowing you to install a \fIdoom\-engine\fP.
.SH AUTHOR
Copyright \(co 2006 Jon Dowland \fI<jon@alcopop.org>\fP.
.br
Thanks to Branden Robinson for his
.URL "http://people.debian.org/~branden/talks/wtfm/" "\(oqWrite the Fine Manual\(cq"
presentation.
.br
\fBmake\-wad\-package\fP is part of \fIdoom-package\fP.
