#!/bin/sh
set -u
set -e

workdir=$(mktemp -td game-data-packager.tests.XXXXXX)
touch "$workdir/yes"

printf "verify_file: "
if   ./tests/lib/verify_file "$workdir/yes" &&
   ! ./tests/lib/verify_file "$workdir/no "; then
    echo pass
else
    echo fail
fi

rm "$workdir/yes"
rmdir "$workdir"
