#!/bin/sh

test_verify_file_yes() {
  ./tests/lib/verify_file "tests/verify_file"
  assertEquals $? 0
}
test_verify_file_no() {
  ./tests/lib/verify_file "tests/does_not_exist"
  assertNotEquals $? 0
}

. ./tests/shunit2/shunit2
